In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6078, 6368, 5141, 9075],
 [6078, 6368, 5141, 9708],
 [6078, 1118, 5141, 2045],
 [6521, 3660, 5089, 5181, 8135],
 [6521, 3660, 5089, 5181, 2631],
 [2029, 6078, 2603, 5141, 9426],
 [4834, 1973, 9860, 5181]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6078 6368 5141 9075]
 [   0    0    0    0 6078 6368 5141 9708]
 [   0    0    0    0 6078 1118 5141 2045]
 [   0    0    0 6521 3660 5089 5181 8135]
 [   0    0    0 6521 3660 5089 5181 2631]
 [   0    0    0 2029 6078 2603 5141 9426]
 [   0    0    0    0 4834 1973 9860 5181]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/opt/anaconda3/envs/MlProjects/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[[-0.00508958,  0.02478477,  0.03470102, -0.00384741,
          0.01297246, -0.03971462,  0.03521197,  0.01780423,
          0.04549226, -0.04863346],
        [-0.00508958,  0.02478477,  0.03470102, -0.00384741,
          0.01297246, -0.03971462,  0.03521197,  0.01780423,
          0.04549226, -0.04863346],
        [-0.00508958,  0.02478477,  0.03470102, -0.00384741,
          0.01297246, -0.03971462,  0.03521197,  0.01780423,
          0.04549226, -0.04863346],
        [-0.00508958,  0.02478477,  0.03470102, -0.00384741,
          0.01297246, -0.03971462,  0.03521197,  0.01780423,
          0.04549226, -0.04863346],
        [ 0.04046342, -0.00280369, -0.02085759,  0.02369864,
          0.0442845 , -0.00581088,  0.00588665,  0.01187322,
          0.00303441,  0.04931468],
        [-0.01012634,  0.03406625, -0.03079504, -0.01818237,
         -0.00646974,  0.04646022,  0.01031983,  0.0221763 ,
          0.02122742, -0.04469948],
        [-0.04082973, -0.0025946 ,  0.00607294,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531